"""m5 payment asaas fields

Revision ID: 6fa9b01b0fce
Revises: fec494f85c21
Create Date: 2026-06-29 15:29:56.116964
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fa9b01b0fce'
down_revision: Union[str, None] = 'fec494f85c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('asaas_customer_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'paid_at')
    op.drop_column('payments', 'due_date')
    op.drop_column('payments', 'asaas_customer_id')
    # ### end Alembic commands ###
