"""b1 case pipeline schema

Revision ID: aa0d737fabc3
Revises: 6fa9b01b0fce
Create Date: 2026-06-29 20:03:05.846496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa0d737fabc3'
down_revision: Union[str, None] = '6fa9b01b0fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), server_default=sa.text("'traffic_fine'"), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('assigned_reviewer', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.2'), nullable=True),
    sa.Column('top_p', sa.Numeric(precision=3, scale=2), server_default=sa.text('1.0'), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type', 'version', name='uq_prompt_templates_type_version')
    )
    op.create_index(op.f('ix_prompt_templates_template_type'), 'prompt_templates', ['template_type'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_table('case_files',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('processing_status', sa.String(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_case_id'), 'case_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_files_user_id'), 'case_files', ['user_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_case_id'), 'processing_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('legal_documents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('storage_file_id', sa.UUID(), nullable=True),
    sa.Column('jurisdiction', sa.String(), server_default=sa.text("'BR'"), nullable=True),
    sa.Column('version_label', sa.String(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_document_type'), 'legal_documents', ['document_type'], unique=False)
    op.create_table('traffic_tickets',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('ait_number', sa.String(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('renavam', sa.String(), nullable=True),
    sa.Column('infraction_code', sa.String(), nullable=True),
    sa.Column('infraction_description', sa.Text(), nullable=True),
    sa.Column('ctb_article', sa.String(), nullable=True),
    sa.Column('infraction_date', sa.Date(), nullable=True),
    sa.Column('infraction_time', sa.Time(), nullable=True),
    sa.Column('infraction_location', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('notification_issue_date', sa.Date(), nullable=True),
    sa.Column('notification_received_date', sa.Date(), nullable=True),
    sa.Column('defense_deadline', sa.Date(), nullable=True),
    sa.Column('officer_id', sa.String(), nullable=True),
    sa.Column('equipment', sa.String(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('illegible_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=True),
    sa.Column('extraction_prompt_version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['case_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_tickets_case_id'), 'traffic_tickets', ['case_id'], unique=False)
    op.create_index(op.f('ix_traffic_tickets_infraction_code'), 'traffic_tickets', ['infraction_code'], unique=False)
    op.create_table('case_analyses',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('possible_arguments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('required_client_inputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['traffic_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_analyses_case_id'), 'case_analyses', ['case_id'], unique=False)
    op.create_table('generated_resources',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('arguments_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ragflow_session_id', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['traffic_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_resources_case_id'), 'generated_resources', ['case_id'], unique=False)
    op.create_index(op.f('ix_generated_resources_status'), 'generated_resources', ['status'], unique=False)
    op.create_table('legal_document_chunks',
    sa.Column('legal_document_id', sa.UUID(), nullable=False),
    sa.Column('ragflow_dataset_id', sa.String(), nullable=True),
    sa.Column('ragflow_document_id', sa.String(), nullable=True),
    sa.Column('ragflow_chunk_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_document_chunks_legal_document_id'), 'legal_document_chunks', ['legal_document_id'], unique=False)
    op.create_table('generated_resource_versions',
    sa.Column('generated_resource_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_resource_id'], ['generated_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_resource_id', 'version', name='uq_genres_version')
    )
    op.create_index(op.f('ix_generated_resource_versions_generated_resource_id'), 'generated_resource_versions', ['generated_resource_id'], unique=False)
    op.drop_index(op.f('ix_prompts_task'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_knowledge_documents_partner_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_type'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('document_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'document_number')
    op.drop_column('users', 'phone')
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('audit_log_actor_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arquivo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('md_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chunks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('knowledge_documents_partner_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_documents_pkey'))
    )
    op.create_index(op.f('ix_knowledge_documents_type'), 'knowledge_documents', ['type'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_partner_id'), 'knowledge_documents', ['partner_id'], unique=False)
    op.create_table('prompts',
    sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prompts_pkey'))
    )
    op.create_index(op.f('ix_prompts_task'), 'prompts', ['task'], unique=False)
    op.drop_index(op.f('ix_generated_resource_versions_generated_resource_id'), table_name='generated_resource_versions')
    op.drop_table('generated_resource_versions')
    op.drop_index(op.f('ix_legal_document_chunks_legal_document_id'), table_name='legal_document_chunks')
    op.drop_table('legal_document_chunks')
    op.drop_index(op.f('ix_generated_resources_status'), table_name='generated_resources')
    op.drop_index(op.f('ix_generated_resources_case_id'), table_name='generated_resources')
    op.drop_table('generated_resources')
    op.drop_index(op.f('ix_case_analyses_case_id'), table_name='case_analyses')
    op.drop_table('case_analyses')
    op.drop_index(op.f('ix_traffic_tickets_infraction_code'), table_name='traffic_tickets')
    op.drop_index(op.f('ix_traffic_tickets_case_id'), table_name='traffic_tickets')
    op.drop_table('traffic_tickets')
    op.drop_index(op.f('ix_legal_documents_document_type'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_case_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_case_files_user_id'), table_name='case_files')
    op.drop_index(op.f('ix_case_files_case_id'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_prompt_templates_template_type'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
