"""m4 analyses fields

Revision ID: fec494f85c21
Revises: 30e68a6436a6
Create Date: 2026-06-29 14:19:30.156306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fec494f85c21'
down_revision: Union[str, None] = '30e68a6436a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('questionario', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('resource_available', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'resource_available')
    op.drop_column('analyses', 'questionario')
    op.drop_column('analyses', 'document_type')
    # ### end Alembic commands ###
